# Generated by Django 5.1.3 on 2024-12-15 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('number_of_pages', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('minimum_points', models.PositiveIntegerField(blank=True, null=True)),
                ('scientific_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='api.scientificdomain')),
            ],
        ),
        migrations.CreateModel(
            name='UserFieldProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_points', models.PositiveIntegerField(default=0)),
                ('scientific_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scientificdomain')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_fields', models.ManyToManyField(blank=True, related_name='interested_users', through='api.UserFieldProgress', to='api.scientificdomain')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userfieldprogress',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
        migrations.CreateModel(
            name='UserArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reading', 'Reading'), ('read', 'Read'), ('reviewed', 'Reviewed')], max_length=10)),
                ('page_left_off', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_articles', to='api.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='userfieldprogress',
            unique_together={('user_profile', 'scientific_domain')},
        ),
    ]
