# Generated by Django 5.1.3 on 2024-12-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userfieldprogress_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfieldprogress',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
