# Generated by Django 5.1.3 on 2024-12-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_review_options_alter_review_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
